### ISSUE TITLE
Please explain or sample with attributes and vendor attributes

### ISSUE THREAD

**Issue by johanteekens** [io-digital/tephra#31]
I've been fiddling around with this project and it seem to work perfectly fine for what I tried. My compliments. I just don't understand how to include  [/* attributes */] and  [/* vendor attributes */] in my server.

Could you please, please elaborate on this or maybe update your example code?

**Comment by skibz** [comment]
hi @johanteekens 
thanks for opening the issue, i will whip something up as soon as possible!

**Comment by skibz** [comment]
@johanteekens 
the best place to refer to is [here](https://github.com/retailnext/node-radius) (the library supporting tephra) -- their examples show instances of the way attributes and vendor specific attributes are declared in packet encoding functions.

with that in mind, some things to take note of:

* [tephra has a deficiency in the way it handles vendor specific attributes](https://github.com/io-digital/tephra/issues/4) (it is unable to encode attributes from more than one vendor)
* when specifying a vendor specific attribute in tephra, you don't specify the vendor id **every time you encode a packet** as it is specified once when initialising your tephra instance (this is a part of the deficiency mentioned above) example: 
```javascript
return accept(
  [ // attributes
    ['attr-1', 'val-1'],
    ['attr-2', 'val-2']
  ],
  [ // vendor attributes
    ['vendor-attr-1', 'vendor-val-1'],
    ['vendor-attr-2', 'vendor-val-2']
  ],
  console.log
)
``` 
* if you're just specifying standard radius attributes into a packet, then it's the same as node-radius, but you still need to specify an empty vendor attributes array, example:
```javascript
return accept(
  [ // attributes
    ['attr-1', 'val-1'],
    ['attr-2', 'val-2']
  ],
  [ // vendor attributes
  ],
  console.log
)
```
* the same goes for not specifying any attributes: just use empty arrays for those arguments. this is a pain point in the tool, and i've been planning to make this nicer for a while (with default arg values, or something like that)

please don't hesitate to get in contact again if this explanation doesn't suffice!

**Comment by johanteekens** [comment]
Awesome, problem solved. works perfectly. I'm actually adding an office 365 authentication module, allowing users to authenticate with office 365 credentials and passing their ACL to the network devices. I just got the thing going using using this module.

**Comment by skibz** [comment]
happy to help!
